image: maven:latest

cache:
  paths:
    - .m2/repository
    - target
    - ~/.npm
    - /home/gitlab-runner/.nvm

deploy-backend:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tee ~/.ssh/id_rsa > /dev/null
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
    - if ! command -v node &> /dev/null || ! command -v pm2 &> /dev/null; then
      apt-get update && apt-get install -y curl;
      curl -sL https://deb.nodesource.com/setup_16.x | bash -;
      apt-get install -y nodejs;
      npm install -g pm2;
      fi
  script:
    - echo "Deploying backend to VPS..."
    - |
      ssh -i ~/.ssh/id_rsa $VPS_USER@$VPS_IP <<'EOF'
        set -e
        cd app/server
        git pull origin main
        mvn clean package
        pm2 delete server || true
        pm2 start java --name "server" -- -jar target/*.jar
        pm2 save
      EOF
  only:
    - main